# Generated by Django 5.2.4 on 2026-08-07 13:43

from django.db import migrations


def set_site_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site, created = Site.objects.get_or_create(
        pk=1,
        defaults={
            'domain': '127.0.0.1:8000',
            'name': 'Authentication Hub',
        }
    )
    if not created:
        site.domain = '127.0.0.1:8000'
        site.name = 'Authentication Hub'
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_site_domain),
    ]
