# Generated by Django 5.2.4 on 2026-08-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_set_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(max_length=254, verbose_name='Email Attempted')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device_info', models.CharField(blank=True, max_length=100, verbose_name='Device')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('session_expired', 'Session Expired')], max_length=20, verbose_name='Event Type')),
                ('success', models.BooleanField(verbose_name='Success')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='accounts_lo_user_id_b24570_idx'), models.Index(fields=['email_attempted'], name='accounts_lo_email_a_ab21b8_idx'), models.Index(fields=['event_type'], name='accounts_lo_event_t_bf08b9_idx'), models.Index(fields=['success'], name='accounts_lo_success_746caa_idx'), models.Index(fields=['timestamp'], name='accounts_lo_timesta_94f63b_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_142937_idx')],
            },
        ),
    ]
