# Generated by Django 5.2.4 on 2026-08-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_login_history'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='accounts_lo_user_id_b24570_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='accounts_lo_success_746caa_idx',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='success',
        ),
    ]
