# Generated by Django 5.2.4 on 2026-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='new_device',
            field=models.BooleanField(default=False, verbose_name='New Device'),
        ),
    ]
