# Generated by Django 5.2.4 on 2026-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginhistory_new_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_throttled', 'Login Throttled'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('session_expired', 'Session Expired')], max_length=20, verbose_name='Event Type'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Attempts')),
                ('first_attempt_at', models.DateTimeField(auto_now_add=True, verbose_name='First Attempt At')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='Last Attempt At')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Blocked Until')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['email'], name='accounts_lo_email_a84d38_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_1f2a14_idx'), models.Index(fields=['last_attempt_at'], name='accounts_lo_last_at_51ad4e_idx'), models.Index(fields=['blocked_until'], name='accounts_lo_blocked_03cd84_idx')],
            },
        ),
    ]
