# Generated by Django 5.2.4 on 2026-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_loginhistory_event_type_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_throttled', 'Login Throttled'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('session_expired', 'Session Expired'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_completed', 'Password Reset Completed')], max_length=30, verbose_name='Event Type'),
        ),
    ]
