# Generated by Django 5.2.4 on 2026-08-13 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_loginhistory_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_login', 'New Login'), ('new_device_login', 'New Device Login'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('account_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('session_expired', 'Session Expired'), ('other_sessions_logged_out', 'Other Sessions Logged Out'), ('email_verified', 'Email Verified')], max_length=30, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device_info', models.CharField(blank=True, max_length=100, verbose_name='Device')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security Notification',
                'verbose_name_plural': 'Security Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_se_user_id_f51cb0_idx'), models.Index(fields=['user', 'created_at'], name='accounts_se_user_id_385303_idx'), models.Index(fields=['notification_type'], name='accounts_se_notific_1c2b8b_idx')],
            },
        ),
    ]
