# Generated by Django 5.2.4 on 2026-08-14 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_securitynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('device_info', models.CharField(blank=True, max_length=100, verbose_name='Device')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Risk Score')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Risk Level')),
                ('risk_reasons', models.TextField(blank=True, verbose_name='Risk Reasons')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('login_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='accounts.loginhistory', verbose_name='Login History')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security Risk Assessment',
                'verbose_name_plural': 'Security Risk Assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_se_user_id_7794e6_idx'), models.Index(fields=['risk_level'], name='accounts_se_risk_le_700165_idx')],
            },
        ),
    ]
