# Generated by Django 5.2.4 on 2026-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_securityriskassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_throttled', 'Login Throttled'), ('login_blocked', 'Login Blocked'), ('logout', 'Logout'), ('session_expired', 'Session Expired'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_completed', 'Password Reset Completed'), ('emergency_security_action', 'Emergency Security Action')], max_length=30, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='securitynotification',
            name='notification_type',
            field=models.CharField(choices=[('new_login', 'New Login'), ('new_device_login', 'New Device Login'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('account_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('session_expired', 'Session Expired'), ('other_sessions_logged_out', 'Other Sessions Logged Out'), ('email_verified', 'Email Verified'), ('emergency_security_action', 'Emergency Security Action')], max_length=30, verbose_name='Notification Type'),
        ),
    ]
